version: '2'
services:
  jhipsterdemoapp-app:
    image: jhipsterdemoapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterdemoapp-mysql:3306/jhipsterdemoapp?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipsterdemoapp-mysql:
    extends:
      file: mysql.yml
      service: jhipsterdemoapp-mysql
